jdbc:
  driverClassName: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://127.0.0.1:3306/springboot_test
  username: root
  password: root

#\u6FC0\u6D3B\u914D\u7F6E\u6587\u4EF6;\u9700\u8981\u6307\u5B9A\u5176\u5B83\u7684\u914D\u7F6E\u6587\u4EF6\u540D\u79F0
spring:
  profiles:
    active: abc,def
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/springboot_test
    username: root
    password: root
  redis:
    host: localhost
    port: 6379
  devtools:
    restart:
      enabled: true  #设置开启热部署
      additional-paths: src/main/java #重启目录
      exclude: WEB-INF/**
  freemarker:
    cache: false    #页面不加载缓存，修改即时生效

#  thymeleaf:
#    prefix:
#      classpath: /templates   # 访问template下的html文件需要配置模板，映射
#    suffix:
#      .html
#    cache: false # 开发时关闭缓存,不然没法看到实时页面

#tomcat端口
server:
  port: 80
#日志记录级别
logging:
  level:
    com.itheima: debug
    org.springframework: info
#mybatis:
#  # 实体类别名包路径
#  type-aliases-package: com.itheima.pojo
#  # 映射文件路径
#  # mapper-locations: classpath:mappers/*.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

mybatis-plus:
  # 实体类别名包路径
  type-aliases-package: com.itheima.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
      #配置日志


#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
